module.exports = {

  "STATUS": {
    "UNAUTHORIZED": {code: 403, message: 'unauthorized'},
    "MISSING_AUTHHEADER": {code: 403, message: 'missing auth header'}
  },
  "API_PRIVILAGE": {

    //Dashboard
    "DASHBOARD_DRIVERDETAILS_GET": "DASHBOARD.DRIVERDETAILS.READ",
    "DASHBOARD_TASKDETAILS_GET": "DASHBOARD.TASKDETAILS.READ",
    "DASHBOARD_TASKLOG_GET": "DASHBOARD.TASKLOG.READ",
    "DASHBOARD_REASSIGNTASK_PUT": "DASHBOARD.REASSIGNTASK.UPDATE",

    //Analytics
    "ANALYTICS_DRIVERLOG_GET": "ANALYTICS.DRIVERLOG.READ",
    "ANALYTICS_ONTIME_GET": "ANALYTICS.ONTIME.READ",
    "ANALYTICS_TASKCOMPLETE_GET": "ANALYTICS.TASKCOMPLETE.READ",
    "ANALYTICS_TOPAGENT_GET": "ANALYTICS.TOPAGENT.READ",

    //Manager
    "MANAGER_GET": "MANAGER.READ",
    "MANAGER_POST": "MANAGER.WRITE",
    "MANAGER_PUT": "MANAGER.UPDATE",
    "MANAGER_DELETE": "MANAGER.DELETE",

    //Team
    "TEAM_GET": "TEAM.READ",
    "TEAM_POST": "TEAM.WRITE",
    "TEAM_PUT": "TEAM.UPDATE",
    "TEAM_DELETE": "TEAM.DELETE",
    "TEAM_ALL_GET": "TEAM.ALL.READ",

    //Customer
    "CUSTOMER_GET": "CUSTOMER.READ",
    "CUSTOMER_PUT": "CUSTOMER.UPDATE",
    "CUSTOMER_DELETE": "CUSTOMER.DELETE",
    "CUSTOMER_IMPORT_POST": "CUSTOMER.IMPORT.WRITE",
    "CUSTOMER_EXPORT_GET": "CUSTOMER.EXPORT.READ",
    "CUSTOMER_ALL_GET": "CUSTOMER.ALL.READ",

    //driver module
    "DRIVER_GET": "DRIVER.READ",
    "DRIVER_POST": "DRIVER.WRITE",
    "DRIVER_PUT": "DRIVER.UPDATE",
    "DRIVER_DELETE": "DRIVER.DELETE",
    "DRIVER_ALL_GET": "DRIVER.ALL.READ",
    "DRIVER_BLOCKUNBLOCK_PUT": "DRIVER.BLOCKUNBLOCK.UPDATE",
    "DRIVER_DRIVERSTATUS_GET": "DRIVER.DRIVERSTATUS.READ",
    "DRIVER_DRIVERSTATUS_POST": "DRIVER.DRIVERSTATUS.WRITE",
    "DRIVER_IMPORT_POST": "DRIVER.IMPORT.WRITE",
    "DRIVER_EXPORT_GET": "DRIVER.EXPORT.READ",


    //task
    "TASK_GET": "TASK.READ",
    "TASK_POST": "TASK.WRITE",
    "TASK_PUT": "TASK.UPDATE",
    "TASK_DELETE": "TASK.DELETE",
    "TASK_CHANGESTATUS_PUT": "TASK.CHANGESTATUS.UPDATE",
    "TASK_TASKDELETE_DELETE": "TASK.TASKDELETE.DELETE",
    "TASK_STATISTICS_GET": "TASK.STATISTICS.READ",
    "TASK_IMPORT_POST": "TASK.IMPORT.WRITE",
    "TASK_EXPORT_GET": "TASK.EXPORT.READ",

    //setting
    "SETTINGS_APPLICATION-SETUP_GET": "SETTINGS.APP.READ",
    "SETTINGS_APPLICATION-SETUP_PUT": "SETTINGS.APP.UPDATE",
    "SETTINGS_AUTO-ALLOCATION_GET": "SETTINGS.ALLOCATION.READ",
    "SETTINGS_AUTO-ALLOCATION_PUT": "SETTINGS.ALLOCATION.UPDATE",
    "SETTINGS_CATEGORY_GET": "SETTINGS.CATEGORY.READ",
    "SETTINGS_CATEGORY_PUT": "SETTINGS.CATEGORY.UPDATE",
    "SETTINGS_NOTIFICATION_GET": "SETTINGS.NOTIFICATION.READ",
    "SETTINGS_NOTIFICATION_PUT": "SETTINGS.NOTIFICATION.UPDATE",
    "SETTINGS_PREFERENCE_GET": "SETTINGS.PREFERENCE.READ",
    "SETTINGS_PREFERENCE_PUT": "SETTINGS.PREFERENCE.UPDATE",
    "SETTINGS_PROFILE_GET": "SETTINGS.PROFILE.READ",
    "SETTINGS_PROFILE_PUT": "SETTINGS.PROFILE.UPDATE",
    "SETTINGS_DEVELOPER_GET": "SETTINGS.DEVELOPER.READ",
    "SETTINGS_DEVELOPER_DELETE": "SETTINGS.DEVELOPER.DELETE",
    "SETTINGS_DEVELOPER_POST": "SETTINGS.DEVELOPER.WRITE",


    // fileipload
    "FILEUPLOAD_POST": "FILEUPLOAD.WRITE",
    "FILEREMOVE_POST": "FILEREMOVE.WRITE",

    // notify
    "NOTIFY_POST": "NOTIFY.WRITE",

    // billing
    "PRICING_INVOICE_GET": "PRICING.INVOICE.READ",
    "PRICING_INVOICEGENERATE_GET": "PRICING.INVOICEGENERATE.READ",
    "PRICING_PACKAGE_GET": "PRICING.PACKAGE.READ",
    "PRICING_PACKAGE_PUT": "PRICING.PACKAGE.UPDATE",
    "PRICING_PAYMENT_POST": "PRICING.PAYMENT.WRITE",
    "PRICING_PLAN_GET": "PRICING.PLAN.READ",
    "PRICING_REMINDER_GET": "PRICING.REMINDER.READ",
    "PRICING_CREDITS_GET": "PRICING.CREDITS.READ"

  },
  "METHOD_MAP": {
    "READ": "GET",
    "WRITE": "POST",
    "UPDATE": "PUT",
    "DELETE": "DELETE"
  },
  "COGNITO": {
    "TOKEN": "access"
  },
  "AUTHORIZE": {
    "ALLOW": 1,
    "DENY": 0
  }
};
